# Generated by Django 3.2.16 on 2025-03-27 09:03

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_group'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user__neq', django.db.models.expressions.F('following'))), name='prevent_self_follow'),
        ),
    ]
