# Generated by Django 3.2.16 on 2025-03-27 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_follow_prevent_self_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='prevent_self_follow',
        ),
    ]
